title: Open Science principles in LangInLife project
description: Reference manual for researchers and administrators
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
