title: Otevřená věda v projektu LangInLife | Open Science in LangInLife project
description: Manuál pro vědkyně*ce a administrativu
logo: /osprinciples/LOGO.png

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-gfm

baseurl: "/osprinciples" 
url: "https://pavla-martinkova.github.io" 
